ignore:
  - "**/*/*.gen.ts"
  - "**/*/coverage.xml"
  - "**/*/coverage-final.json"
  - "**/*/coverage/**"
  - "**/*/node_modules/**"
  - "**/*/dist/**"
  - "**/*/build/**"
  - "**/*/.test.*"
  - "**/*/version.ts"
comment:
    layout: "condensed_header, condensed_files, condensed_footer"
    hide_project_coverage: TRUE
