{{- if .Values.ingress.enabled }}
{{- $fullName := include "assist.fullname" . -}}
{{- $socketioSvcPort := .Values.service.ports.socketio -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "assist.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # Extract sessionID from peerId using regex
      if ($arg_peerId ~ ".*-(?<extracted_sid>[^-]+)-.*") {
        set $session_id $extracted_sid;
      }
      add_header X-Debug-Session-ID $session_id;
      add_header X-Debug-Session-Type "wss";
    nginx.ingress.kubernetes.io/upstream-hash-by: $session_id

  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: "{{ tpl .Values.ingress.className . }}" 
  tls:
    - hosts:
        - {{ .Values.global.domainName }}
      {{- if .Values.ingress.tls.secretName}}
      secretName: {{ .Values.ingress.tls.secretName }}
      {{- end}}
  rules:
    - host: {{ .Values.global.domainName }} 
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $socketioSvcPort }}
            path: /ws-assist/(.*)
{{- end }}
